import { BookData } from "../types";
import { peoplesTales } from "./peoples-tales";
import { crownsSecrets } from "./crowns-secrets";
import { merchantsLedger } from "./merchants-ledger";

/**
 * BOOK DATA - COMBINED INDEX
 * ===========================
 * 
 * This file combines all three path data files into the final bookData structure.
 * 
 * TO ADD QUESTIONS:
 * 1. Open the appropriate path file:
 *    - peoples-tales.ts - Daily life, folklore, traditions
 *    - crowns-secrets.ts - Political history, rulers, wars
 *    - merchants-ledger.ts - Economic history, trade, industry
 * 
 * 2. Add your country and questions following the existing format
 * 
 * 3. The changes will automatically be included here
 * 
 * DO NOT edit this file directly - edit the individual path files instead!
 */

// Get all unique country names from all three paths
const allCountries = new Set([
  ...Object.keys(peoplesTales),
  ...Object.keys(crownsSecrets),
  ...Object.keys(merchantsLedger)
]);

// Build the combined bookData structure
export const bookData: BookData = {};

for (const country of allCountries) {
  bookData[country] = {
    "People's Tales": peoplesTales[country] || [],
    "Crown's Secrets": crownsSecrets[country] || [],
    "Merchant's Ledger": merchantsLedger[country] || []
  };
}
